//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplicante()
        {
            this.ExperienciaLaborales = new HashSet<ExperienciaLaborale>();
            this.GradoEstudios = new HashSet<GradoEstudio>();
            this.Recomendaciones = new HashSet<Recomendacione>();
            this.Idiomas = new HashSet<Idioma>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdPosicion { get; set; }
        public int Salario_Esperado { get; set; }
        public Nullable<System.DateTime> Fecha_Ultima_Aplicacion { get; set; }
        public string Cedula { get; set; }
        public string Estado { get; set; }
        public string Empresa { get; set; }
    
        public virtual Posicione Posicione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciaLaborale> ExperienciaLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradoEstudio> GradoEstudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacione> Recomendaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Idioma> Idiomas { get; set; }
        public virtual Aplicante Aplicantes1 { get; set; }
        public virtual Aplicante Aplicante1 { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual Educ_Continua Educ_Continua { get; set; }
    }
}
