//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educ_Continua
    {
        public int IDEducacionContinua { get; set; }
        public int IDAplicante { get; set; }
        public Nullable<int> Costo { get; set; }
        public string Descripcion { get; set; }
        public string Duracion { get; set; }
        public string Empresa { get; set; }
    
        public virtual Aplicante Aplicante { get; set; }
    }
}
