//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RRHHEntities : DbContext
    {
        public RRHHEntities()
            : base("name=RRHHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplicante> Aplicantes { get; set; }
        public virtual DbSet<ExperienciaLaborale> ExperienciaLaborales { get; set; }
        public virtual DbSet<GradoEstudio> GradoEstudios { get; set; }
        public virtual DbSet<Idioma> Idiomas { get; set; }
        public virtual DbSet<Posicione> Posiciones { get; set; }
        public virtual DbSet<Recomendacione> Recomendaciones { get; set; }
    }
}
